<!DOCTYPE html>
<html lang="zh-cn">
	<head>
	    <meta charset="UTF-8">
		<title>滕州有有有，吃喝玩乐，应有尽有</title>
		<meta name="description" content="滕州最好玩的网络平台，（住房，工作，服务，全新，二手，婚恋，交友，车辆，求购，出售，宠物）各种信息" />
		<link href="/asset/css/base.css" rel="stylesheet">
	</head>
	<body>
		<nav>
			<ul>
				<li class="site_name"><a href="/">滕州</a></li>
				<li><a href="/">有有有</a></li>
				<!--li><a href="http://tzuuu.com/ttt">游游游</a></li>
				<li><a href="#">搜索</a></li -->
			</ul>
		</nav>
