<?php include VIEW_PATH . '/head.phtml'; ?>

	<div class="success_container">
		<h1>操作成功!  <?php echo $info?></h1>
		<h2 class="jump">
			页面自动 <a id="href" href="<?php echo $url?>">跳转</a> 等待时间： <b id="wait"><?php echo $time?></b>
		</h2>
	</div>
	
	<script type="text/javascript">
	(function(){
	var wait = document.getElementById('wait'),href = document.getElementById('href').href;
	var interval = setInterval(function(){
		var time = --wait.innerHTML;
		if(time <= 0) {
			location.href = href;
			clearInterval(interval);
		};
	}, 1000);
	})();
	</script>
		
<?php include VIEW_PATH . '/foot.phtml'; ?>